language: objective-c
os: osx
osx_image: xcode7.3
xcode_project: MovingHelper.xcodeproj
xcode_scheme: MovingHelperTests
xcode_sdk: iphonesimulator9.3

env:
  - TOOLCHAINS=swift
script:
  - swift build --fetch
before_install:
  - TOOLCHAIN_VERSION=swift-DEVELOPMENT-SNAPSHOT-2016-03-24-a
  - curl -O https://swift.org/builds/development/xcode/${TOOLCHAIN_VERSION}/${TOOLCHAIN_VERSION}-osx.pkg
  - sudo installer -pkg ${TOOLCHAIN_VERSION}-osx.pkg -target /
